function render({ slots: ___SLOTS___ }) {
		return `<!DOCTYPE html> <html> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width,initial-scale=1"> <title>TOPO portal (es)</title> <script src="https://aframe.io/releases/1.5.0/aframe.min.js"></script> <script src="https://cdn.jsdelivr.net/npm/@8thwall/engine-binary@1/dist/xr.js" crossorigin="anonymous" data-preload-chunks="slam"></script> <script src="https://cdn.jsdelivr.net/npm/@8thwall/xrextras@1/dist/xrextras.js" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/gh/c-frame/aframe-extras@7.0.0/dist/aframe-extras.min.js"></script> <link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Contrail+One&display=swap" rel="stylesheet"> </head> <body> <script src="bundle.es.js"></script> <div id="loading-screen"></div> <div id="crosshair"></div> <div id="transition-overlay"></div> <div id="experience-hud"> <span id="zone-label">Andén</span> </div> <div id="overlay" style="display:none" class="absolute-fill"> <img id="recenterButton" src="assets/textures/recenter.png"> <button id="gridToggleBtn" class="grid-btn">GRID</button> </div> <a-scene preloader responsive-immersive intro-flow debug-grid surface-quality variant-selector tap-to-place-portal station-manager portal-ground-effect vr-mode-ui="enabled: false" xrextras-loading xrextras-runtime-error renderer="colorManagement: true;" xrweb="allowedDevices: any; disableDefaultEnvironment: true;"> <a-assets> <a-asset-item id="portal-frame-model" src="assets/models/Portal_frame.glb"></a-asset-item> <a-asset-item id="portal-door-01-model" src="assets/models/Portal_Door_01.glb"></a-asset-item> <a-asset-item id="portal-door-02-model" src="assets/models/Portal_Door_02.glb"></a-asset-item> <img id="station-360-img" src="assets/textures/station-360.jpg"> <img id="exit-a-360-img" src="assets/textures/exit-a-360.jpg"> <img id="portal-glow-img" src="assets/textures/portal-glow.png"> <img id="icon-plus" src="assets/images/Plus.svg"> <img id="icon-aspa" src="assets/images/aspa.svg"> </a-assets> <a-camera id="camera" portal-camera position="0 9 11"> </a-camera> <xrextras-opaque-background remove="true"> <a-entity id="hider-walls"> <a-box scale="100 1 100" position="0 -1 49" xrextras-hider-material></a-box> <a-box scale="100 100 1" position="0 50 75" xrextras-hider-material></a-box> <a-box scale="100 1 100" position="0 100 49" xrextras-hider-material></a-box> <a-box scale="1 100 100" position="-30 50 50" xrextras-hider-material></a-box> <a-box scale="1 100 100" position="30 50 50" xrextras-hider-material></a-box> </a-entity> </xrextras-opaque-background> <a-entity id="directional-light" light="
      type: directional;
      intensity: 0.2;
      castShadow: true;
      shadowMapHeight:2048;
      shadowMapWidth:2048;
      shadowCameraTop: 35;
      shadowCameraBottom: -20;
      shadowCameraRight: 40;
      shadowCameraLeft: -10;
      target: #portalRim" xrextras-attach="target: portalRim; offset: 18 7 14" shadow> </a-entity> <a-light id="secondary-light" type="hemisphere" color="#CEE4F0" groundColor="#332211" intensity="0.8"></a-light> <a-entity id="portal-contents"> <a-sky src="#station-360-img" rotation="0 -90 0"></a-sky> <a-entity data-station="station-entrance" hotspot="key: 0" position="0 10 -40"> </a-entity> <a-entity data-station="station-entrance" hotspot="key: 1" position="20 6 -35"> </a-entity> <a-entity data-station="station-entrance" hotspot="key: 2" position="-25 8 -30"> </a-entity> </a-entity> <a-entity id="portal-root" scale="1.4 1.4 1.4" visible="false"> <a-plane id="portal-stencil-mask" width="3.4" height="8.51" position="0 6.71 0.05" material="shader: flat; color: #000" visible="false"></a-plane> <a-entity id="portal-window" geometry="primitive: sphere; radius: 50; segmentsWidth: 64; segmentsHeight: 32" material="shader: flat; src: #station-360-img; side: back" position="0 0 0" rotation="0 -90 0" scale="-1 1 1" visible="false"></a-entity> <a-entity id="portal-wall"> <a-plane width="7" height="14" rotation="0 180 0" position="0 6.71 0" xrextras-hider-material></a-plane> <a-plane width="7" height="14" rotation="0 180 0" position="0 6.71 0.3" xrextras-hider-material></a-plane> </a-entity> <a-plane id="portal-glow" width="3.4" height="8.51" position="0 6.71 0" material="shader: flat; src: #portal-glow-img; transparent: true; depthWrite: false; blending: additive; side: double"></a-plane> <a-entity id="elevator-doors" elevator-doors="width: 0; openOffset: 1.7; clipHalfWidth: 1.7" position="0 2.45 0"> <a-entity id="door-left" gltf-model="#portal-door-01-model" scale="4.3 4.3 4.3"></a-entity> <a-entity id="door-right" gltf-model="#portal-door-02-model" scale="4.3 4.3 4.3"></a-entity> </a-entity> <a-entity id="portalRim" gltf-model="#portal-frame-model" reflections="type: realtime" position="0 2.45 0" rotation="0 0 0" scale="4.3 4.3 4.3" shadow="receive: false"></a-entity> </a-entity> </a-scene> </body> </html> `
	}
render["astro:html"] = true;

const _page = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
      __proto__: null,
      default: render
}, Symbol.toStringTag, { value: 'Module' }));

const page = () => _page;

export { page };
